### ISSUE TITLE
Regarding Assignment Problems

### ISSUE THREAD

**Issue by jKhurana** [bogatyy/cs228#1]
Hello Bogatty,

I am reading the online notes of the course CS228. To understand the material more better, I want to do theoretical and practical assignment. Can I get them from somewhere ?

Even if this is not an issue related to this, I am posting it here as haven't found any another place.

Thank you so much for your co-operations.

**Comment by bogatyy** [comment]
Hey! http://cs.stanford.edu/~ermon/cs228/index.html and https://ermongroup.github.io/cs228-notes/
